<?php

/**
 * BaseWeaponStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $weapon_id
 * @property integer $stat_id
 * @property integer $kills
 * @property integer $deaths
 * @property Weapon $Weapon
 * @property Stat $Stat
 * 
 * @method integer    getWeaponId()  Returns the current record's "weapon_id" value
 * @method integer    getStatId()    Returns the current record's "stat_id" value
 * @method integer    getKills()     Returns the current record's "kills" value
 * @method integer    getDeaths()    Returns the current record's "deaths" value
 * @method Weapon     getWeapon()    Returns the current record's "Weapon" value
 * @method Stat       getStat()      Returns the current record's "Stat" value
 * @method WeaponStat setWeaponId()  Sets the current record's "weapon_id" value
 * @method WeaponStat setStatId()    Sets the current record's "stat_id" value
 * @method WeaponStat setKills()     Sets the current record's "kills" value
 * @method WeaponStat setDeaths()    Sets the current record's "deaths" value
 * @method WeaponStat setWeapon()    Sets the current record's "Weapon" value
 * @method WeaponStat setStat()      Sets the current record's "Stat" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseWeaponStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('weapon_stat');
        $this->hasColumn('weapon_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('stat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('kills', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('deaths', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Weapon', array(
             'local' => 'weapon_id',
             'foreign' => 'id'));

        $this->hasOne('Stat', array(
             'local' => 'stat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}