<?php

/**
 * BasePlayer
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $numeric_steamid
 * @property string $steamid
 * @property string $credential
 * @property string $name
 * @property timestamp $last_login
 * @property integer $views
 * @property string $avatar_url
 * @property Doctrine_Collection $Log
 * @property Doctrine_Collection $Stats
 * @property Doctrine_Collection $PlayerStats
 * @property Doctrine_Collection $Event
 * @property Doctrine_Collection $EventPlayers
 * 
 * @method integer             getId()              Returns the current record's "id" value
 * @method integer             getNumericSteamid()  Returns the current record's "numeric_steamid" value
 * @method string              getSteamid()         Returns the current record's "steamid" value
 * @method string              getCredential()      Returns the current record's "credential" value
 * @method string              getName()            Returns the current record's "name" value
 * @method timestamp           getLastLogin()       Returns the current record's "last_login" value
 * @method integer             getViews()           Returns the current record's "views" value
 * @method string              getAvatarUrl()       Returns the current record's "avatar_url" value
 * @method Doctrine_Collection getLog()             Returns the current record's "Log" collection
 * @method Doctrine_Collection getStats()           Returns the current record's "Stats" collection
 * @method Doctrine_Collection getPlayerStats()     Returns the current record's "PlayerStats" collection
 * @method Doctrine_Collection getEvent()           Returns the current record's "Event" collection
 * @method Doctrine_Collection getEventPlayers()    Returns the current record's "EventPlayers" collection
 * @method Player              setId()              Sets the current record's "id" value
 * @method Player              setNumericSteamid()  Sets the current record's "numeric_steamid" value
 * @method Player              setSteamid()         Sets the current record's "steamid" value
 * @method Player              setCredential()      Sets the current record's "credential" value
 * @method Player              setName()            Sets the current record's "name" value
 * @method Player              setLastLogin()       Sets the current record's "last_login" value
 * @method Player              setViews()           Sets the current record's "views" value
 * @method Player              setAvatarUrl()       Sets the current record's "avatar_url" value
 * @method Player              setLog()             Sets the current record's "Log" collection
 * @method Player              setStats()           Sets the current record's "Stats" collection
 * @method Player              setPlayerStats()     Sets the current record's "PlayerStats" collection
 * @method Player              setEvent()           Sets the current record's "Event" collection
 * @method Player              setEventPlayers()    Sets the current record's "EventPlayers" collection
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayer extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('player');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('numeric_steamid', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('steamid', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('credential', 'string', 10, array(
             'type' => 'string',
             'default' => 'user',
             'notnull' => true,
             'length' => 10,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 100,
             ));
        $this->hasColumn('last_login', 'timestamp', null, array(
             'type' => 'timestamp',
             'notnull' => false,
             ));
        $this->hasColumn('views', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => false,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('avatar_url', 'string', 75, array(
             'type' => 'string',
             'notnull' => false,
             'length' => 75,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Log', array(
             'local' => 'id',
             'foreign' => 'submitter_player_id'));

        $this->hasMany('Stat as Stats', array(
             'local' => 'id',
             'foreign' => 'player_id'));

        $this->hasMany('PlayerStat as PlayerStats', array(
             'local' => 'id',
             'foreign' => 'player_id'));

        $this->hasMany('Event', array(
             'local' => 'id',
             'foreign' => 'attacker_player_id'));

        $this->hasMany('EventPlayer as EventPlayers', array(
             'local' => 'id',
             'foreign' => 'player_id'));
    }
}