<?php

/**
 * BaseSession
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $sdata
 * @property timestamp $stime
 * 
 * @method string    getSdata() Returns the current record's "sdata" value
 * @method timestamp getStime() Returns the current record's "stime" value
 * @method Session   setSdata() Sets the current record's "sdata" value
 * @method Session   setStime() Sets the current record's "stime" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseSession extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('session');
        $this->hasColumn('sdata', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('stime', 'timestamp', null, array(
             'type' => 'timestamp',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}