<?php

/**
 * BasePlayerHealStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $player_id
 * @property integer $stat_id
 * @property integer $healing
 * @property Player $Player
 * @property Stat $Stat
 * 
 * @method integer        getPlayerId()  Returns the current record's "player_id" value
 * @method integer        getStatId()    Returns the current record's "stat_id" value
 * @method integer        getHealing()   Returns the current record's "healing" value
 * @method Player         getPlayer()    Returns the current record's "Player" value
 * @method Stat           getStat()      Returns the current record's "Stat" value
 * @method PlayerHealStat setPlayerId()  Sets the current record's "player_id" value
 * @method PlayerHealStat setStatId()    Sets the current record's "stat_id" value
 * @method PlayerHealStat setHealing()   Sets the current record's "healing" value
 * @method PlayerHealStat setPlayer()    Sets the current record's "Player" value
 * @method PlayerHealStat setStat()      Sets the current record's "Stat" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayerHealStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('player_heal_stat');
        $this->hasColumn('player_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('stat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('healing', 'integer', 3, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 3,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Player', array(
             'local' => 'player_id',
             'foreign' => 'id'));

        $this->hasOne('Stat', array(
             'local' => 'stat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}