<?php

/**
 * BaseServerGroup
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $slug
 * @property string $name
 * @property integer $owner_id
 * @property Doctrine_Collection $Servers
 * 
 * @method string              getSlug()     Returns the current record's "slug" value
 * @method string              getName()     Returns the current record's "name" value
 * @method integer             getOwnerId()  Returns the current record's "owner_id" value
 * @method Doctrine_Collection getServers()  Returns the current record's "Servers" collection
 * @method ServerGroup         setSlug()     Sets the current record's "slug" value
 * @method ServerGroup         setName()     Sets the current record's "name" value
 * @method ServerGroup         setOwnerId()  Sets the current record's "owner_id" value
 * @method ServerGroup         setServers()  Sets the current record's "Servers" collection
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseServerGroup extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('server_group');
        $this->hasColumn('slug', 'string', 30, array(
             'type' => 'string',
             'notnull' => true,
             'unique' => true,
             'length' => 30,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('owner_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Server as Servers', array(
             'local' => 'id',
             'foreign' => 'server_group_id'));
    }
}