<?php

/**
 * BaseTrack
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $url
 * @property integer $hits
 * 
 * @method string  getUrl()  Returns the current record's "url" value
 * @method integer getHits() Returns the current record's "hits" value
 * @method Track   setUrl()  Sets the current record's "url" value
 * @method Track   setHits() Sets the current record's "hits" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseTrack extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('track');
        $this->hasColumn('url', 'string', 255, array(
             'type' => 'string',
             'unique' => true,
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('hits', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        
    }
}