<?php

/**
 * BaseItemPickupStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property integer $stat_id
 * @property string $item_key_name
 * @property integer $times_picked_up
 * @property Stat $Stat
 * 
 * @method integer        getId()              Returns the current record's "id" value
 * @method integer        getStatId()          Returns the current record's "stat_id" value
 * @method string         getItemKeyName()     Returns the current record's "item_key_name" value
 * @method integer        getTimesPickedUp()   Returns the current record's "times_picked_up" value
 * @method Stat           getStat()            Returns the current record's "Stat" value
 * @method ItemPickupStat setId()              Sets the current record's "id" value
 * @method ItemPickupStat setStatId()          Sets the current record's "stat_id" value
 * @method ItemPickupStat setItemKeyName()     Sets the current record's "item_key_name" value
 * @method ItemPickupStat setTimesPickedUp()   Sets the current record's "times_picked_up" value
 * @method ItemPickupStat setStat()            Sets the current record's "Stat" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseItemPickupStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('item_pickup_stat');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('stat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('item_key_name', 'string', 20, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 20,
             ));
        $this->hasColumn('times_picked_up', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Stat', array(
             'local' => 'stat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}