<?php

/**
 * BaseUsedWeapon
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $weapon_id
 * @property integer $stat_id
 * @property Weapon $Weapon
 * @property Stat $Stat
 * 
 * @method integer    getWeaponId()  Returns the current record's "weapon_id" value
 * @method integer    getStatId()    Returns the current record's "stat_id" value
 * @method Weapon     getWeapon()    Returns the current record's "Weapon" value
 * @method Stat       getStat()      Returns the current record's "Stat" value
 * @method UsedWeapon setWeaponId()  Sets the current record's "weapon_id" value
 * @method UsedWeapon setStatId()    Sets the current record's "stat_id" value
 * @method UsedWeapon setWeapon()    Sets the current record's "Weapon" value
 * @method UsedWeapon setStat()      Sets the current record's "Stat" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseUsedWeapon extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('used_weapon');
        $this->hasColumn('weapon_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('stat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Weapon', array(
             'local' => 'weapon_id',
             'foreign' => 'id'));

        $this->hasOne('Stat', array(
             'local' => 'stat_id',
             'foreign' => 'id'));
    }
}