<?php

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $redscore
 * @property integer $bluescore
 * @property Doctrine_Collection $Stats
 * @property LogFile $LogFile
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getName()      Returns the current record's "name" value
 * @method integer             getRedscore()  Returns the current record's "redscore" value
 * @method integer             getBluescore() Returns the current record's "bluescore" value
 * @method Doctrine_Collection getStats()     Returns the current record's "Stats" collection
 * @method LogFile             getLogFile()   Returns the current record's "LogFile" value
 * @method Log                 setId()        Sets the current record's "id" value
 * @method Log                 setName()      Sets the current record's "name" value
 * @method Log                 setRedscore()  Sets the current record's "redscore" value
 * @method Log                 setBluescore() Sets the current record's "bluescore" value
 * @method Log                 setStats()     Sets the current record's "Stats" collection
 * @method Log                 setLogFile()   Sets the current record's "LogFile" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 100,
             ));
        $this->hasColumn('redscore', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
        $this->hasColumn('bluescore', 'integer', 4, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 4,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Stat as Stats', array(
             'local' => 'id',
             'foreign' => 'log_id'));

        $this->hasOne('LogFile', array(
             'local' => 'id',
             'foreign' => 'log_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}