<?php

/**
 * BasePlayerStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $player_id
 * @property integer $stat_id
 * @property integer $kills
 * @property integer $deaths
 * @property Player $Player
 * @property Stat $Stat
 * 
 * @method integer    getPlayerId()  Returns the current record's "player_id" value
 * @method integer    getStatId()    Returns the current record's "stat_id" value
 * @method integer    getKills()     Returns the current record's "kills" value
 * @method integer    getDeaths()    Returns the current record's "deaths" value
 * @method Player     getPlayer()    Returns the current record's "Player" value
 * @method Stat       getStat()      Returns the current record's "Stat" value
 * @method PlayerStat setPlayerId()  Sets the current record's "player_id" value
 * @method PlayerStat setStatId()    Sets the current record's "stat_id" value
 * @method PlayerStat setKills()     Sets the current record's "kills" value
 * @method PlayerStat setDeaths()    Sets the current record's "deaths" value
 * @method PlayerStat setPlayer()    Sets the current record's "Player" value
 * @method PlayerStat setStat()      Sets the current record's "Stat" value
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BasePlayerStat extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('player_stat');
        $this->hasColumn('player_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('stat_id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => false,
             ));
        $this->hasColumn('kills', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
        $this->hasColumn('deaths', 'integer', 2, array(
             'type' => 'integer',
             'notnull' => true,
             'default' => 0,
             'length' => 2,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Player', array(
             'local' => 'player_id',
             'foreign' => 'id'));

        $this->hasOne('Stat', array(
             'local' => 'stat_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));
    }
}