<?php

/**
 * BaseLog
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $name
 * @property integer $redscore
 * @property integer $bluescore
 * @property timestamp $created_at
 * @property timestamp $updated_at
 * @property Doctrine_Collection $Stats
 * 
 * @method integer             getId()         Returns the current record's "id" value
 * @method string              getName()       Returns the current record's "name" value
 * @method integer             getRedscore()   Returns the current record's "redscore" value
 * @method integer             getBluescore()  Returns the current record's "bluescore" value
 * @method timestamp           getCreatedAt()  Returns the current record's "created_at" value
 * @method timestamp           getUpdatedAt()  Returns the current record's "updated_at" value
 * @method Doctrine_Collection getStats()      Returns the current record's "Stats" collection
 * @method Log                 setId()         Sets the current record's "id" value
 * @method Log                 setName()       Sets the current record's "name" value
 * @method Log                 setRedscore()   Sets the current record's "redscore" value
 * @method Log                 setBluescore()  Sets the current record's "bluescore" value
 * @method Log                 setCreatedAt()  Sets the current record's "created_at" value
 * @method Log                 setUpdatedAt()  Sets the current record's "updated_at" value
 * @method Log                 setStats()      Sets the current record's "Stats" collection
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLog extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('log');
        $this->hasColumn('id', 'integer', null, array(
             'type' => 'integer',
             'primary' => true,
             'autoincrement' => true,
             ));
        $this->hasColumn('name', 'string', 100, array(
             'type' => 'string',
             'length' => 100,
             ));
        $this->hasColumn('redscore', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('bluescore', 'integer', 4, array(
             'type' => 'integer',
             'length' => 4,
             ));
        $this->hasColumn('created_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
        $this->hasColumn('updated_at', 'timestamp', 25, array(
             'type' => 'timestamp',
             'length' => 25,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Stat as Stats', array(
             'local' => 'id',
             'foreign' => 'log_id'));
    }
}