<?php

/**
 * Event
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 */
class Event extends BaseEvent {
  public function kill($elapsedSeconds, $attackerPlayerId, $attackerCoord, $victimPlayerId, $victimCoord) {
    $this->event_type = "kill";
    $this->elapsed_seconds = $elapsedSeconds;
    $this->attacker = $attackerPlayerId;
    $this->attacker_coord = $attackerCoord;
    $this->victim = $victimPlayerId;
    $this->victim_coord = $victimCoord;
  }
  
  public function assist($assistPlayerId, $assistCoord) {
    $this->assist = $assistPlayerId;
    $this->assist_coord = $assistCoord;
  }
  
  public function chat($elapsedSeconds, $chatType, $playerId, $text) {
    $this->elapsed_seconds = $elapsedSeconds;
    $this->event_type = $chatType;
    $this->player_id = $playerId;
    $this->text = $text;
  }
}
