<?php

/**
 * EventPlayerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventPlayerTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventPlayerTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EventPlayer');
    }
}