<?php

/**
 * EventTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EventTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EventTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Event');
    }
    
    public function getEventsByIdAsArray($id) {
      return $this
        ->createQuery('e')
        ->leftJoin('e.Log l')
        ->leftJoin('e.EventPlayers ep')
        ->where('l.id = ?', $id)
        ->orderBy('e.elapsed_seconds asc, e.id asc')
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
        ->execute();
    }
    
    public function getChatEventsByIdAsArray($id) {
      return $this
        ->createQuery('e')
        ->leftJoin('e.Log l')
        ->leftJoin('e.EventPlayers ep')
        ->where('l.id = ?', $id)
        ->whereIn('e.event_type', array('say', 'say_team'))
        ->orderBy('e.elapsed_seconds asc, e.id asc')
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
        ->execute();
    }
}
