<?php

/**
 * LogFileTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogFileTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogFileTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogFile');
    }
}