<?php

/**
 * LogLineTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogLineTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object LogLineTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('LogLine');
    }
}