<?php

/**
 * LogTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class LogTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object LogTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Log');
    }
    
    public function getLogById($id) {
      $l = Doctrine::getTable('Log')
      ->createQuery('l')
      ->where('l.id = ?', $id)
      ->innerJoin('l.Stats s')
      ->orderBy('s.team, s.name')
      ->execute();
      return $l[0];
    }
}
