<?php

/**
 * RoleStatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class RoleStatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object RoleStatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('RoleStat');
    }
}