<?php

/**
 * ServerTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ServerTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object ServerTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Server');
    }
    
    /**
      Checks if the given IP and port combination are being used by another active user. If it is, return true, else false.
    */
    public function isAddressUsed($ip, $port) {
      if(!$ip || !$port) throw new IllegalArgumentException('IP and port cannot be null for isAddressUsed method.');
      
      $q = $this
        ->createQuery('s')
        ->select('count(s.id)')
        ->where('s.ip = ?', $ip)
      ->andWhere('s.port = ?', $port)
      ->andWhere('s.status != ?', Server::STATUS_INACTIVE);

      $c = (int) $q->fetchOne(array(), Doctrine_Core::HYDRATE_SINGLE_SCALAR);
      
      return $c != 0;
    }
}
