<?php

/**
 * Server
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Server extends BaseServer {
  public function saveNewServer($slug, $name, $ip, $port, $owner_id) {
    $serverGroup = new ServerGroup();
    $serverGroup->setSlug($slug);
    $serverGroup->setName($name);
    $serverGroup->setOwnerId($owner_id);
    
    $this->ip = $ip;
    $this->port = $port;
    $this->ServerGroup = $serverGroup;
    
    $this->validate_key = 'asdf';
    $this->status = 'N'; //for not validated
    
    $this->save();
  }
  
  public function getSlug() {
    if(!$this->slug) return $this->ServerGroup->getSlug();
    return $this->slug;
  }
}
