<?php

/**
 * SessionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class SessionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object SessionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Session');
    }
}