<?php

/**
 * Stat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Brian Barnekow
 */
class Stat extends BaseStat {  
  /**
  * Sets the attributes found in the PlayerInfo object into this object.
  */
  function setPlayerInfoAttributes(PlayerInfo $playerInfo) {
    if(!isset($this->Player)) {
      $p = Doctrine::getTable('Player')->findOneBySteamid($playerInfo->getSteamid());
      if($p != null) $this->setPlayer($p);
      else {
        $p = new Player();
        $p->setSteamid($playerInfo->getSteamid());
        $p->save();
        $this->Player = $p;
      }
    }
    $this->setName($playerInfo->getName());
    $this->setTeam($playerInfo->getTeam());
  }
  
  /**
  * Convenience method to determine if this stat record is equal to
  * the given playerInfo.
  */
  public function equalsPlayerInfo(PlayerInfo $playerInfo) {
    return $this->getPlayer()->getSteamid() == $playerInfo->getSteamid();
  }
  
  /**
  * Gets the columns that can be incremented,
  * by filtering out certain values.
  */
  protected function getStatColumns() {
    return array_diff($this->getTable()->getColumnNames(), array('id', 'log_id', 'name', 'steamid', 'team'));
  }
  
  /**
  * Checks to see if the given statkey can be incremented.
  */
  protected function isKeyAbleToBeIncremented($statkey) {
    foreach($this->getStatColumns() as $col) {
      if($statkey == $col) return true;
    }
    return false;
  }
  
  /**
  * Increments the stat, if the key exists. Otherwise, it throws an exception.
  */
  public function incrementStat($statkey, $increment = 1) {
    if(!$this->isKeyAbleToBeIncremented($statkey)) {
      throw new InvalidArgumentException("Invalid key '$statkey' given to incrementStat method.");
    }
    
    $this->_set($statkey, $this->_get($statkey)+$increment);
  }
  
  /**
  * Calculates the stat's kills per death ratio.
  */
  public function getKillsPerDeath() {
    return $this->doPerDeathDivision($this->getKills());
  }
  
  /**
  * Calculates the stat's ubers per death ratio.
  */
  public function getUbersPerDeath() {
    return $this->doPerDeathDivision($this->getUbers());
  }
  
  protected function doPerDeathDivision($numerator) {
    if($this->getDeaths() == 0) return $numerator;
    return round((float) $numerator/$this->getDeaths(), 3);
  }
  
  /**
  * This will add the given weapon to the player's stats.
  */
  public function incrementWeaponForPlayer($weapon, $propertyToIncrement, $increment = 1) {
    $addws = true;
    foreach($this->WeaponStats as &$ws) {
      if($ws->getWeaponId() == $weapon->getId()) {
        $ws->_set($propertyToIncrement, $ws->_get($propertyToIncrement)+$increment);
        $addws = false;
        break;
      }
    }
    if($addws) {
      $wsadd = new WeaponStat();
      $wsadd->setWeaponId($weapon->getId());
      $wsadd->setStat($this);
      $wsadd->_set($propertyToIncrement, $increment);
      $this->WeaponStats[] = $wsadd;
    }
  }
  
  /**
  * This will add the given player to this player's stats.
  */
  public function addPlayerStat($otherPlayer, $propertyToIncrement, $increment = 1) {
    $addps = true;
    foreach($this->PlayerStats as &$ps) {
      if($ps->getPlayerId() == $otherPlayer->getId()) {
        //echo "[update ".$this->getPlayer()->getSteamid()." add '$propertyToIncrement' with player ".$otherPlayer->getSteamId()."]        ";
        $ps->_set($propertyToIncrement, $ps->_get($propertyToIncrement)+$increment);
        $addps = false;
        break;
      }
    }
    if($addps) {
      //echo "[add ".$this->getPlayer()->getSteamid()." id ".$this->getPlayer()->getId()." add '$propertyToIncrement' with player ".$otherPlayer->getSteamId()." id ".$otherPlayer->getId()."]        ";
      $psadd = new PlayerStat();
      $psadd->setPlayerId($otherPlayer->getId());
      $psadd->setStat($this);
      $psadd->_set($propertyToIncrement, $increment);
      $this->PlayerStats[] = $psadd;
    }
  }
  
  /**
  * This will add the given role to the player's stats.
  * If the role does not exist in the database, an exception is thrown.
  */
  public function addRoleToPlayer($role) {
    $this->Roles[] = $role;
  }
  
  public function addRoleToPlayerFromWeapon($weapon) {
    $role = $weapon->getRole();
    if($role && $role->getKeyName() != null) $this->Roles[] = $role;
  }
}
