<?php

/**
 * UsedWeaponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsedWeaponTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsedWeaponTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsedWeapon');
    }
}