<?php

/**
 * UsedRoleTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class UsedRoleTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object UsedRoleTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('UsedRole');
    }
}