<?php

/**
 * WeaponStatTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WeaponStatTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object WeaponStatTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('WeaponStat');
    }
}