<?php

/**
 * WeaponStat
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    tf2logs
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class WeaponStat extends BaseWeaponStat {
  public static function createWeaponStat($weaponId, $propertyToIncrement, $increment = 1) {
    return array(
      'weapon_id' => $weaponId,
      'kills' => 0,
      'deaths' => 0,
      $propertyToIncrement => $increment //this will either be kills or deaths, and this will override the defaults above.
    );
  }
}
