<?php

/**
 * WeaponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WeaponTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object WeaponTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Weapon');
    }
    
    public function getAllWeapons() {
      return $this
        ->createQuery('w')
        ->leftJoin('w.Role r')
        ->orderBy('w.name asc')
        ->execute();
    }
}
