<?php

/**
 * WeaponTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class WeaponTable extends Doctrine_Table {
    /**
     * Returns an instance of this class.
     *
     * @return object WeaponTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('Weapon');
    }
    
    public function getAllWeapons() {
      return $this
        ->createQuery('w')
        ->leftJoin('w.Role r')
        ->orderBy('w.name asc')
        ->execute();
    }
    
    /**
    * Gets unique weapons that were used in the log
    */
    public function getWeaponsForLogId($logid) {
      return $this
        ->createQuery('w')
        ->innerJoin('w.WeaponStat ws')
        ->innerJoin('ws.Stat s')
        ->innerJoin('s.Log l')
        ->where('l.id = ?', $logid)
        ->orderBy('w.name')
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
        ->execute();
    }
    
    /**
    * Gets unique weapons that were used in the log, however this only gets the weapon data directly.
    */
    public function getMiniWeaponsForLogId($logid) {
      return Doctrine_Query::create()
        ->select('w.id, w.name, w.key_name, w.image_name')
        ->from('Weapon w')
        ->innerJoin('w.WeaponStat ws')
        ->innerJoin('ws.Stat s')
        ->innerJoin('s.Log l')
        ->where('l.id = ?', $logid)
        ->orderBy('w.name')
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
        ->execute();
    }
    
    /**
    * Gets unique weapons that a player died or killed with
    */
    public function getWeaponsForPlayerId($playerId) {
      return $this
        ->createQuery('w')
        ->innerJoin('w.WeaponStat ws')
        ->innerJoin('ws.Stat s')
        ->innerJoin('s.Player p')
        ->where('p.numeric_steamid = ?', $playerId)
        ->orderBy('w.name')
        ->setHydrationMode(Doctrine_Core::HYDRATE_ARRAY)
        ->execute();
    }
}
