# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/05-Factories

prod:
  logger:
    class: sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
      
qa:
  logger:
    class: sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log
      
staging:
  logger:
    class: sfFileLogger
    param:
      level:   err
      loggers: ~
      file:    %SF_LOG_DIR%/%SF_APP%_%SF_ENVIRONMENT%.log

test:
  storage:
    class: sfSessionTestStorage
    param:
      session_path: %SF_TEST_CACHE_DIR%/sessions

  response:
    class: sfWebResponse
    param:
      send_http_headers: false

  mailer:
    param:
      delivery_strategy: none

dev:
  mailer:
    param:
      delivery_strategy: none

all:
  routing:
    class: sfPatternRouting
    param:
      generate_shortest_url:            true
      extra_parameters_as_query_string: true

  view_cache_manager:
    class: sfViewCacheManager
    param:
      cache_key_use_vary_headers: true
      cache_key_use_host_name:    true
      
  storage:
    class: sfPDOSessionStorage
    param:
      session_name: tf2logs
      db_table:     session
      database:     doctrine
      db_id_col:    id
      db_data_col:  sdata
      db_time_col:  stime
