# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: log, action: index }
  
log_by_id:
  url:   /log/:id
  param: { module: log, action: show }
  requirements: {id: \d+}
  
events_by_id:
  url:   /log/:id/events
  param: { module: log, action: events }
  requirements: {id: \d+, sf_format: json}
  
log_create:
  url:   /log/add
  param: { module: log, action: add }
  
player_by_numeric_steamid:
  url:   /player/:id
  param: { module: player, action: showNumericSteamId }
  requirements: {id: \d+}
  
player_search:
  url:   /player/search/
  param: { module: player, action: search }
  
controlpanel:
  url:   /player/controlPanel
  param: { module: player, action: controlPanel }
  
autoLogin:
  url:   /player/autoLogin
  param: { module: player, action: autoLogin }
  
logout:
  url:   /player/logout
  param: { module: player, action: logout }
  
openid_finishauth:
  url: /player/finish
  param: { module: player, action: finish }
  
openid_error:
  url: /player/openidError
  param: { module: player, action: openidError }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
