# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/10-Routing

# default rules
homepage:
  url:   /
  param: { module: log, action: index }
  
whats_new:
  url: /whatsnew
  param: {module: content, action: whatsNew}
  
plugins:
  url: /plugins
  param: {module: content, action: plugins}
  
log_by_id:
  url:   /logs/:id
  param: { module: log, action: show }
  requirements: {id: \d+}
  
log_edit:
  url:   /logs/:id/edit
  param: { module: log, action: edit }
  requirements: {id: \d+}
  
log_update:
  url:   /logs/:id/update
  param: { module: log, action: update }
  requirements: {id: \d+}
  
events_by_id:
  url:   /logs/:id/events
  param: { module: log, action: events }
  requirements: {id: \d+, sf_format: json}

logfile:
  url:   /logs/:id/logfile
  param: { module: log, action: logfile }
  requirements: {id: \d+}
  
log_create:
  url:   /logs/add
  param: { module: log, action: add }
  
player_by_numeric_steamid:
  url:   /players/:id
  param: { module: player, action: showNumericSteamId }
  requirements: {id: \d+}
  
log_search:
  url:   /logs/search
  param: { module: log, action: search }
  
player_search:
  url:   /players/search
  param: { module: player, action: search }
  
controlpanel:
  url:   /my
  param: { module: player, action: controlPanel }
  
autoLogin:
  url:   /players/autoLogin
  param: { module: player, action: autoLogin }
  
logout:
  url:   /players/logout
  param: { module: player, action: logout }
  
openid_finishauth:
  url: /players/finish
  param: { module: player, action: finish }
  
openid_error:
  url: /players/openidError
  param: { module: player, action: openidError }

# generic rules
# please, remove them by adding more specific rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
