# You can find more information about this file on the symfony website:
# http://www.symfony-project.org/reference/1_4/en/08-Security

finish:
  is_secure: false
  
autoLogin:
  is_secure: false
  
showNumericSteamId:
  is_secure: false
  
show:
  is_secure: false
  
events:
  is_secure: false
  
logfile:
  is_secure: false
  
whatsNew:
  is_secure: false
  
faq:
  is_secure: false
  
plugins:
  is_secure: false
  
search:
  is_secure: false
  
index:
  is_secure: false

#defaulting to secure for owners and users. This will only contain user level operations.
default:
  is_secure: true
  credentials: [[owner, user]]
