options:
  type: INNODB
  collate: utf8_general_ci
  charset: utf8
  
test:
  doctrine:
    param:
      dsn:  mysql:dbname=tf2logs_test;host=localhost
      
dev:
  doctrine:
    param:
      dsn:  mysql:dbname=tf2logs_dev;host=localhost
      
prod:
  doctrine:
    param:
      dsn:  mysql:dbname=tf2logs;host=localhost
 
all:
  doctrine:
    class: sfDoctrineDatabase
    param:
      username: root
      password: null
      attributes:
        default_table_collate: utf8_general_ci
        default_table_charset: utf8
