Log:
  actAs: [Timestampable]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    name:
      type: string(100)
      notnull: true
    redscore:
      type: integer(4)
      notnull: true
      default: 0
    bluescore:
      type: integer(4)
      notnull: true
      default: 0

Stat:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    log_id:
      type: integer
      notnull: true
    name:
      type: string(100)
      notnull: true
    steamid:
      type: string(30)
      notnull: true
    team:
      type: string(4)
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    assists:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
    longest_kill_streak:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_blocked:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_captured:
      type: integer(4)
      notnull: true
      default: 0
    dominations:
      type: integer(4)
      notnull: true
      default: 0
    times_dominated:
      type: integer(4)
      notnull: true
      default: 0
    revenges:
      type: integer(4)
      notnull: true
      default: 0
    builtobjects:
      type: integer(4)
      notnull: true
      default: 0
    destroyedobjects:
      type: integer(4)
      notnull: true
      default: 0
    extinguishes:
      type: integer(4)
      notnull: true
      default: 0
    ubers:
      type: integer(4)
      notnull: true
      default: 0
    dropped_ubers:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Log: 
      onDelete: CASCADE
      foreignAlias: Stats
    Weapons:
      foreignAlias: Stats
      class: Weapon
      refClass: UsedWeapon
    Roles:
      foreignAlias: Stats
      class: Role
      refClass: UsedRole
      
LogFile:
  columns:
    log_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    log_data:
      type: clob(16777215)
      notnull: true
  relations:
    Log:
      onDelete: CASCADE
      foreignAlias: LogFile
      foreignType: one
      
Weapon:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(20)
      notnull: true
    name:
      type: string(30)
      notnull: false
    role_id:
      type: integer
      primary: false
      autoincrement: false
      notnull: false
  relations:
    Role:
      foreignAlias: Weapon
      foreignType: one
      
UsedWeapon:
  columns:
    weapon_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
  relations:
    Weapon:
      foreignAlias: UsedWeapons
    Stat:
      foreignAlias: UsedWeapons

Role:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(12)
      notnull: true
    name:
      type: string(20)
      notnull: false
      
UsedRole:
  columns:
    role_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
  relations:
    Role:
      foreignAlias: UsedRoles
    Stat:
      foreignAlias: UsedRoles
