Log:
  actAs: [Timestampable]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    name:
      type: string(100)
      notnull: true
    redscore:
      type: integer(4)
      notnull: true
      default: 0
    bluescore:
      type: integer(4)
      notnull: true
      default: 0
    elapsed_time:
      type: integer
      notnull: true
      default: 0
    error_log_name:
      type: string(50)
      notnull: false
    error_exception:
      type: string(500)
      notnull: false
  relations:
    LogFile:
      local: id
      foreign: log_id

Stat:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    log_id:
      type: integer
      notnull: true
    name:
      type: string(100)
      notnull: true
    player_id:
      type: integer
      notnull: true
    team:
      type: string(4)
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    assists:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
    longest_kill_streak:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_blocked:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_captured:
      type: integer(4)
      notnull: true
      default: 0
    dominations:
      type: integer(4)
      notnull: true
      default: 0
    times_dominated:
      type: integer(4)
      notnull: true
      default: 0
    revenges:
      type: integer(4)
      notnull: true
      default: 0
    builtobjects:
      type: integer(4)
      notnull: true
      default: 0
    destroyedobjects:
      type: integer(4)
      notnull: true
      default: 0
    extinguishes:
      type: integer(4)
      notnull: true
      default: 0
    ubers:
      type: integer(4)
      notnull: true
      default: 0
    dropped_ubers:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Log:
      onDelete: CASCADE
      foreignAlias: Stats
    Weapons:
      foreignAlias: Stats
      class: Weapon
      refClass: WeaponStat
    Roles:
      foreignAlias: Stats
      class: Role
      refClass: RoleStat
    Player: 
      foreignAlias: Stats
    Players:
      foreignAlias: Stats
      class: Player
      refClass: PlayerStat
      
LogFile:
  columns:
    log_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    log_data:
      type: clob(16777215)
      notnull: true
  relations:
    Log:
      foreignAlias: LogFile
      foreignType: one
      
Weapon:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(40)
      notnull: true
    name:
      type: string(40)
      notnull: false
    role_id:
      type: integer
      primary: false
      autoincrement: false
      notnull: false
  relations:
    Role:
      foreignAlias: Weapon
      foreignType: one
      
WeaponStat:
  columns:
    weapon_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Weapon:
      foreignAlias: WeaponStats
    Stat:
      onDelete: CASCADE
      foreignAlias: WeaponStats

Role:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(12)
      notnull: true
    name:
      type: string(20)
      notnull: false
      
RoleStat:
  columns:
    role_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    time_played:
      type: integer
      notnull: true
      default: 0
  relations:
    Role:
      foreignAlias: RoleStats
    Stat:
      onDelete: CASCADE
      foreignAlias: RoleStats

Player:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    numeric_steamid:
      type: integer
      notnull: true
    steamid:
      type: string(30)
      notnull: true
    credential:
      type: string(10)
      default: user
      notnull: true
      
PlayerStat:
  columns:
    player_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Player:
      foreignAlias: PlayerStats
    Stat:
      onDelete: CASCADE
      foreignAlias: PlayerStats
