Log:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    name:
      type: string(100)
    redscore:
      type: integer(4)
    bluescore:
      type: integer(4)
    created_at:
      type: timestamp(25)
    updated_at:
      type: timestamp(25)

Stat:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
    log_id:
      type: integer
    name:
      type: string(100)
    steamid:
      type: string(30)
    team:
      type: string(4)
    kills:
      type: integer(4)
    assists:
      type: integer(4)
    deaths:
      type: integer(4)
    kills_per_death:
      type: integer(4)
    longest_kill_streak:
      type: integer(4)
    capture_points_blocked:
      type: integer(4)
    capture_points_captured:
      type: integer(4)
    dominations:
      type: integer(4)
    times_dominated:
      type: integer(4)
    revenges:
      type: integer(4)
    builtobjects:
      type: integer(4)
    destroyedobjects:
      type: integer(4)
    extinguishes:
      type: integer(4)
    ubers:
      type: integer(4)
    dropped_ubers:
      type: integer(4)
    ubers_per_death:
      type: integer(4)
  relations:
    Log: 
      onDelete: CASCADE
      foreignAlias: Stats
