Log:
  actAs: [Timestampable]
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    name:
      type: string(100)
      notnull: true
    redscore:
      type: integer(4)
      notnull: true
      default: 0
    bluescore:
      type: integer(4)
      notnull: true
      default: 0
    elapsed_time:
      type: integer
      notnull: true
      default: 0
    map_name:
      type: string(50)
      notnull: false
    submitter_player_id:
      type: integer
      notnull: false
    error_log_name:
      type: string(50)
      notnull: false
    error_exception:
      type: string(500)
      notnull: false
  relations:
    LogFile:
      local: id
      foreign: log_id
    Submitter:
      local: submitter_player_id
      class: Player

Stat:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    log_id:
      type: integer
      notnull: true
    name:
      type: string(100)
      notnull: true
    player_id:
      type: integer
      notnull: true
    team:
      type: string(4)
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    assists:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
    damage:
      type: integer(4)
      notnull: true
      default: 0
    longest_kill_streak:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_blocked:
      type: integer(4)
      notnull: true
      default: 0
    capture_points_captured:
      type: integer(4)
      notnull: true
      default: 0
    dominations:
      type: integer(4)
      notnull: true
      default: 0
    times_dominated:
      type: integer(4)
      notnull: true
      default: 0
    revenges:
      type: integer(4)
      notnull: true
      default: 0
    extinguishes:
      type: integer(4)
      notnull: true
      default: 0
    ubers:
      type: integer(4)
      notnull: true
      default: 0
    dropped_ubers:
      type: integer(4)
      notnull: true
      default: 0
    healing:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Log:
      onDelete: CASCADE
      foreignAlias: Stats
    Weapons:
      foreignAlias: Stats
      class: Weapon
      refClass: WeaponStat
    Roles:
      foreignAlias: Stats
      class: Role
      refClass: RoleStat
    Player: 
      foreignAlias: Stats
    Players:
      foreignAlias: Stats
      class: Player
      refClass: PlayerStat
  indexes:
    name_idx:
      fields: [name]
      
LogFile:
  columns:
    log_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    log_data:
      type: clob(16777215)
      notnull: true
  relations:
    Log:
      foreignAlias: LogFile
      foreignType: one
      
Weapon:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(40)
      notnull: true
      unique: true
    name:
      type: string(40)
      notnull: false
    role_id:
      type: integer
      primary: false
      autoincrement: false
      notnull: false
  relations:
    Role:
      foreignAlias: Weapon
      foreignType: one
      
WeaponStat:
  columns:
    weapon_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
    damage:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Weapon:
      foreignAlias: WeaponStats
    Stat:
      onDelete: CASCADE
      foreignAlias: WeaponStats

Role:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    key_name:
      type: string(12)
      notnull: true
    name:
      type: string(20)
      notnull: false
      
RoleStat:
  columns:
    role_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    time_played:
      type: integer
      notnull: true
      default: 0
  relations:
    Role:
      foreignAlias: RoleStats
    Stat:
      onDelete: CASCADE
      foreignAlias: RoleStats

Player:
  columns:
    id:
      type: integer
      primary: true
      autoincrement: true
      notnull: true
    numeric_steamid:
      type: integer
      notnull: true
      unique: true
    steamid:
      type: string(30)
      notnull: true
      unique: true
    credential:
      type: string(10)
      default: user
      notnull: true
    name:
      type: string(100)
      notnull: false
      
PlayerStat:
  columns:
    player_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    stat_id:
      type: integer
      primary: true
      autoincrement: false
      notnull: true
    kills:
      type: integer(4)
      notnull: true
      default: 0
    deaths:
      type: integer(4)
      notnull: true
      default: 0
  relations:
    Player:
      foreignAlias: PlayerStats
    Stat:
      onDelete: CASCADE
      foreignAlias: PlayerStats
      
Event:
  columns:
    log_id:
      type: integer
      notnull: true
    event_type:
      type: string(10)
      notnull: true
    elapsed_seconds:
      type: integer(4)
      notnull: true
    attacker_player_id:
      type: integer
      notnull: false
    attacker_coord:
      type: string(17)
      notnull: false
    victim_player_id:
      type: integer
      notnull: false
    victim_coord:
      type: string(17)
      notnull: false
    assist_player_id:
      type: integer
      notnull: false
    assist_coord:
      type: string(17)
      notnull: false
    chat_player_id:
      type: integer
      notnull: false
    text:
      type: string(255)
      notnull: false
    team:
      type: string(4)
      notnull: false
    capture_point:
      type: string(30)
      notnull: false
    blue_score:
      type: integer(4)
      notnull: false
    red_score:
      type: integer(4)
      notnull: false
    weapon_id:
      type: integer
      notnull: false
  relations:
    Log:
      onDelete: CASCADE
      foreignAlias: Events
    Attacker:
      local: attacker_player_id
      class: Player
    Victim:
      local: victim_player_id
      class: Player
    Assist:
      local: assist_player_id
      class: Player
    Chat:
      local: chat_player_id
      class: Player
    Weapon:
      onDelete: CASCADE
      foreignAlias: Weapons
      
EventPlayer:
  columns:
    event_id:
      type: integer
      notnull: true
    event_player_type:
      type: string(1)
      notnull: true
    player_id:
      type: integer
      notnull: true
  relations:
    Player:
      onDelete: CASCADE
      foreignAlias: EventPlayers
    Event:
      onDelete: CASCADE
      foreignAlias: EventPlayers
